# Generated by Django 3.0.5 on 2021-01-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Eashan Panjwani', 'EP'), ('Zach Bell', 'ZB'), ('Benner Mullin', 'BM'), ('Jackson Brodwolf', 'JB'), ('Matt Halper', 'MH'), ('Alex Hazel', 'AH'), ('Harris Klein', 'HK'), ('Kohl Terry', 'KT'), ('Alex Mellas', 'AM'), ('Noah Paige', 'NP'), ('Julian Ricci', 'JR'), ('Robbie Kramer', 'RK'), ('Ethan Roberts', 'ER'), ('Henry Rogers', 'HR'), ('Ryan Simon', 'RS'), ('Peter Netch', 'PN'), ('Andrew Schanny', 'AS'), ('Avery Friedman', 'AF'), ('Josh Greenfield', 'JG'), ('Will Spartin', 'WS'), ('Will Goldberg', 'WG'), ('Brady Sheaffer', 'BS'), ('Aman Patil', 'AP'), ('Zach Stern', 'ZS'), ('Josh Josef', 'JJ'), ('Nico Simon', 'NS'), ('Sam Schoepke', 'SS'), ('James Berthoud', 'JBe'), ('Jonathan Nurko', 'JN'), ('Spencer Gladstone', 'SG'), ('Kion Noori', 'KN'), ('Max Marchetto', 'MM'), ('Chuck Leonetti', 'CL'), ('Matt Flower', 'MF'), ('Connor Caz', 'CC'), ('Caleb Hughes', 'CH'), ('Lukas Steinbock', 'LS'), ('Brian Volk', 'BV')], max_length=50)),
                ('elo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Eashan Panjwani', 'EP'), ('Zach Bell', 'ZB'), ('Benner Mullin', 'BM'), ('Jackson Brodwolf', 'JB'), ('Matt Halper', 'MH'), ('Alex Hazel', 'AH'), ('Harris Klein', 'HK'), ('Kohl Terry', 'KT'), ('Alex Mellas', 'AM'), ('Noah Paige', 'NP'), ('Julian Ricci', 'JR'), ('Robbie Kramer', 'RK'), ('Ethan Roberts', 'ER'), ('Henry Rogers', 'HR'), ('Ryan Simon', 'RS'), ('Peter Netch', 'PN'), ('Andrew Schanny', 'AS'), ('Avery Friedman', 'AF'), ('Josh Greenfield', 'JG'), ('Will Spartin', 'WS'), ('Will Goldberg', 'WG'), ('Brady Sheaffer', 'BS'), ('Aman Patil', 'AP'), ('Zach Stern', 'ZS'), ('Josh Josef', 'JJ'), ('Nico Simon', 'NS'), ('Sam Schoepke', 'SS'), ('James Berthoud', 'JBe'), ('Jonathan Nurko', 'JN'), ('Spencer Gladstone', 'SG'), ('Kion Noori', 'KN'), ('Max Marchetto', 'MM'), ('Chuck Leonetti', 'CL'), ('Matt Flower', 'MF'), ('Connor Caz', 'CC'), ('Caleb Hughes', 'CH'), ('Lukas Steinbock', 'LS'), ('Brian Volk', 'BV')], max_length=50)),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_1', models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50)),
                ('character_2', models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50)),
                ('avg_elo', models.IntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='ranks.Player')),
                ('player1entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1entry', to='ranks.PlayerEntry')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='ranks.Player')),
                ('player2entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2entry', to='ranks.PlayerEntry')),
            ],
        ),
        migrations.CreateModel(
            name='ACT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='ranks.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='ranks.Team')),
                ('team3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t3', to='ranks.Team')),
                ('team4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t4', to='ranks.Team')),
            ],
        ),
    ]
