# Generated by Django 3.1.5 on 2021-01-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_auto_20210114_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='act',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='act',
            name='team3',
        ),
        migrations.RemoveField(
            model_name='act',
            name='team4',
        ),
        migrations.RemoveField(
            model_name='race',
            name='points',
        ),
        migrations.AddField(
            model_name='act',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t1character_1',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t1character_2',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t1player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1p1', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t1player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1p2', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t2character_1',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t2character_2',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t2player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2p1', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t2player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2p2', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t3character_1',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t3character_2',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t3player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3p1', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t3player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3p2', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t4character_1',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t4character_2',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Toad', 'Toad'), ('Koopa', 'Koopa'), ('Bowser Jr.', 'Bowser Jr.'), ('Diddy Kong', 'Diddy Kong'), ('Medium character', 'Medium character'), ('Big character', 'Big character')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='t4player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t4p1', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='act',
            name='t4player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t4p2', to='ranks.player'),
        ),
        migrations.AddField(
            model_name='race',
            name='points1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='points2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='points3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='points4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='team1racer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1entry', to='ranks.playerentry'),
        ),
        migrations.AddField(
            model_name='race',
            name='team2racer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2entry', to='ranks.playerentry'),
        ),
        migrations.AddField(
            model_name='race',
            name='team3racer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3entry', to='ranks.playerentry'),
        ),
        migrations.AddField(
            model_name='race',
            name='team4racer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t4entry', to='ranks.playerentry'),
        ),
    ]
