# Generated by Django 3.1.5 on 2021-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0004_auto_20210123_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='eightpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eightteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='elevenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='elevenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='elevenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='elevenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eleventeam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eleventeam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eleventeam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='eleventeam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fifteenteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fivepoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fivepoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fivepoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fivepoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fiveteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fiveteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fiveteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fiveteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='fourteenteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='ninepoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='ninepoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='ninepoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='ninepoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='nineteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='nineteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='nineteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='nineteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='onepoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='onepoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='onepoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='onepoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='oneteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='oneteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='oneteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='oneteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sevenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sevenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sevenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sevenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='seventeam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='seventeam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='seventeam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='seventeam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='sixteenteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='tenteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenpoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenpoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenpoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenpoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='thirteenteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threepoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threepoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threepoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threepoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threeteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threeteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threeteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='threeteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelvepoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelvepoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelvepoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelvepoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelveteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelveteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelveteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twelveteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twopoints1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twopoints2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twopoints3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twopoints4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twoteam1racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twoteam2racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twoteam3racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='twoteam4racer',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2')], max_length=50, null=True),
        ),
    ]
