# Generated by Django 3.1.5 on 2021-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0008_auto_20210825_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='baby_baby',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='baby_baby_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='bowser_baby',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='bowser_baby_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='bowser_diddy',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='bowser_diddy_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='bowser_koopa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='bowser_koopa_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='diddy_baby',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='diddy_baby_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='diddy_koopa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='diddy_koopa_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='koopa_baby',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='koopa_baby_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='koopa_koopa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='koopa_koopa_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='others',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='others_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='score_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_baby',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_baby_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_bowser',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_bowser_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_diddy',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_diddy_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_koopa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_koopa_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='total_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
