# Generated by Django 3.1.5 on 2021-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0009_auto_20210825_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_bowser',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_bowser_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_diddy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='toad_diddy_count',
            field=models.IntegerField(default=0),
        ),
    ]
