# Generated by Django 3.1.5 on 2021-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0011_auto_20210825_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='score_sd',
            field=models.FloatField(default=0),
        ),
    ]
