# Generated by Django 3.1.5 on 2021-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0012_auto_20210825_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvariables',
            name='sum_sq',
            field=models.IntegerField(default=0),
        ),
    ]
